### ISSUE TITLE
Breaking changes in 0.3.2, still on Packagist

### ISSUE THREAD

**Issue by sforward** [twikey/twikey-api-php#13]
Hi, we ran into unexpected breaking changes in constructor of `Twikey\Api\Twikey` in the latest version installed via composer. That version was 0.3.2, but I don't see that tag in the repository anymore, so I assume it was removed already. Could you please update Packagist?

**Comment by koen-serry** [comment]
Hi, you're right, the constructor changed indeed. We needed to do this fix as the user-agent couldn't be passed (which is helpful in case where the client can't actually tell us what happened) as well as the move from api.twikey.com to the more merchant specific api url. As this "breaks" the semantic versioning I've just added a couple of more endpoints as well as added the subscription gateway and pushed out v.0.4.0.

Apologies for the inconvenience.
