### ISSUE TITLE
Get all mandates for a customer

### ISSUE THREAD

**Issue by rvvincelli** [twikey/twikey-api-php#3]
Hi @koen-serry! I am looking for a way to fetch all mandates a customer has, with the customer identified by ID. Mollie has [it](https://docs.mollie.com/reference/v2/mandates-api/list-mandates).

Your [update feed](https://www.twikey.com/api/index.html?php#update-feed) is stateful: one only gets updates to the mandates collection. I would not like to have to maintain the state myself, it is quite cumbersome.

How do you suggest to address this?

Thanks,

**Comment by koen-serry** [comment]
Hi @rvvincelli we currently do not offer a mandates per customer (although it's on our roadmap) The update feed is stateful (but on our end), this means that we keep track of the last mandate you've retrieved. So every time you as us the feed we'll return you anything you haven't seen yet. You might look at it best as a queue you read until empty. 

This way you can keep a synced database of mandates on your end, which you'll probably want for sending out transactions to the bank at one point or another.

**Comment by rvvincelli** [comment]
Hi @koen-serry , thanks for your answer. I am curious why you opted for a stateful approach on your end, seeing that a known REST principle is statelessness. It does help to look at it as a queue and I see it supports a webhook mechanism too.

For our use case we will have to maintain a state on our end then. This comes with some extra design and implementation effort, unfortunately.

**Comment by rvvincelli** [comment]
Hi @koen-serry , another point which is not clear to us is the way you manage pagination in the update feeds.

From the api docs: _Note: it's important to keep reading the response until no more update is available. This way you're sure that every update is handled._ , and you have a `chunkSize` header too. But from the example it is not really clear if you provide explicit paging or not.

Say that there are more than 100 (the stated maximum) updated entries from our last call, like 142: may we assume that you will return 100 records, and that at the next call we will get the remaining 42?

Please illustrate, thanks,

**Comment by rvvincelli** [comment]
@koen-serry @abojic can you clarify on the point above when you have a little time? Thanks :)

**Comment by rvvincelli** [comment]
A little context on where I am coming from actually... :) Together with @umalasomma we are taking care of the implementation of a Twikey-based payment interface for a client. The client codename is IGL and the CSM responsible for it on your side is Bart B. We want to deliver the work before mid September. Thanks!

**Comment by koen-serry** [comment]
Hi @rvvincelli you're correct in your assumption, but I'm unclear how to illustrate :) So by default the chunk size is 100 and if you happen to have 142, you'll get the first 100 in the first call and the remainder in the second. But the code hides that from you as the 2 http calls are done one after another and you'll only need to implement the callback which will be called 142 times.

**Comment by rvvincelli** [comment]
Hi @koen-serry , thanks for clarifying this. The implementation of our callbacks is OK, and as the paging is implicit as you suggest, if we have 142 we will get 100 at the first call, and to get the extra 42 we will have to call you again. Thanks,
